### ISSUE TITLE
How the hell can you make this bump without a breaking change version bump?

### ISSUE THREAD

**Issue by lonewarrior556** [hapijs/pez#22]
How the hell do you make this change and only patch bump @hueniverse??  
```
  "engines": {
    "node": ">=8.9.0"
    "node": ">=8.12.0"
```
https://github.com/hapijs/pez/commit/3eedd49951b7a56cfa20afff10cabd337e0f9d8b

**Comment by hueniverse** [comment]
I actually found myself taking a few moments to think how to respond to this rude, obnoxious, and generally misguided issue opened by someone who just doesn't know what "the hell" they are talking about.

I came up with a few options:

## The high road

I could explain to you that this is something we do on routine maintenance. As a matter of policy, we only support the very latest version of node for each major branch since our CI only tests the very latest. However, it would be too time consuming to update dozens of package.json files all the time so we update them when we work on other cleanup tasks.

There is nothing breaking about this. The `engines` field is a not enforced by npm. You can still use any version you want. It just tells you which versions are officially supported. If for some reason your configuration is one where this creates problems, you should simply fix your node version to one that contains all the latest security and bug fixes.

# The middle road

I was initially going to just close this issue saying "it is not a breaking change" and point you to [this](https://docs.npmjs.com/files/package.json#engines) and then to [this](https://docs.npmjs.com/files/package.json#enginestrict) pointing out this could only be a problem if you use npm v1 or v2.

# The road taken

However, after much reflection I've decided the best was to respond to this issue is to skip the high road and the middle road and just to tell you to go fuck yourself.

Therefore, go fuck yourself.
